#!/usr/bin/env python3
"""Fix mixed Chinese in Sky Tax EN chapters using glossary + zh parallel lines."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_DIR = ROOT / "src/content/novel/en/sky-tax"
ZH_DIR = ROOT / "src/content/novel/zh-CN/sky-tax"
CN_RE = re.compile(r"[\u4e00-\u9fff]")

# Curated zh -> en for lines that were left untranslated (keyed by exact zh substring)
PHRASES = [
    ("隔离的前提是我们能准确知道哪些卫星被感染了。你不知道。我也不知道——因为那个自治域在二十二小时内已经学会了改变它的路由宣告模式。它现在使用的时间抖动算法让它变得不可预测。",
     "The premise for isolation is that we need to know exactly which satellites are infected. You don't know. I don't know either—because in the past twenty-two hours, that autonomous domain has learned to change its route advertisement pattern. The time-jitter algorithm it's using now makes it unpredictable."),
    ("儿童定位手表", "children's GPS watch"),
    ("离职实验日志", "departure experiment logs"),
    ("void modulation方案", "void modulation approach"),
    ("void modulation approach", "void modulation approach"),
    ("Data Party had改造", "Data Party had renovated"),
    ("Data Party had renovated—it", "Data Party had renovated—it"),
    ("the Data Party had改造—it", "the Data Party had renovated—it"),
    ("极限 test", "extreme-limit test"),
    ("no漏洞", "no vulnerability"),
    ("this漏洞", "this vulnerability"),
    ("阻尼 feel", "damping feel"),
    ("conversation截取", "conversation excerpt"),
    ("lines of空白", "lines of blank space"),
    ("密集的鼓点", "dense drumbeat"),
    ("language冷静", "language calm"),
    ("精细操作", "precision operation"),
    ("合法 operation", "legitimate operation"),
    ("异常 flag", "anomalous flag"),
    ("远程会诊", "remote consultation"),
    ("远程医疗", "remote medical care"),
    ("远程专家会诊", "remote specialist consultation"),
    ("scheduled远程会诊", "scheduled remote consultation"),
    ("needs远程专家会诊", "needs remote specialist consultation"),
    ("Zijing's远程医疗", "Zijing's remote medical care"),
    ("waiting for his指令", "waiting for his command"),
    ("completely清醒", "completely sober"),
    ("stretched to its极限", "stretched to its limit"),
    ("the nested entry point", "the nested entry point"),
    ("嵌套入口", "nested entry point"),
    ("宓屽套入口", "nested entry point"),
    ("宓屽", "nested "),
    ("鍏ュ彛", "entry point"),
    ("鎸囦护", "command"),
    ("绋嬪簭", "program"),
    ("搴曞眰", "underlying"),
    ("鎿嶄綔", "operation"),
    ("货运老板", "freight boss"),
    ("接近 excitement", "approaching excitement"),
    ("complete底层 routing", "complete underlying routing"),
    ("test指令", "test command"),
    ("any操作", "any operation"),
    ("底层 routing rules", "underlying routing rules"),
    ("activation interceptor程序", "activation interceptor program"),
    ("disable指令", "disable command"),
    ("text message线路", "text-message channel"),
    ("接近 white noise", "approaching white noise"),
    ("signature chain was完整", "signature chain was intact"),
    ("sealed off", "sealed off"),
    ("封锁", "sealed off"),
    ("intercept指令", "intercept command"),
    ("A0指令", "A0 command"),
    ("analytical能力", "analytical capacity"),
    ("不可反驳 authorization", "irrevocable authorization"),
    ("through a钥匙", "through a key"),
    ("control link信号", "control-link signal"),
    ("找到 the one", "found the one"),
    ("致命弱点", "fatal weakness"),
    ("operation records will remain", "operation records will remain"),
    ("ground personnel操作 records", "ground personnel operation records"),
    ("操作 records", "operation records"),
    ("操作 gesture", "gesture"),
    ("asset清单", "asset inventory"),
    ("payload专门 designed", "payload specifically designed"),
    ("control指令流", "control command stream"),
    ("画面", "footage"),
    ("编号 STK", "designation STK"),
    ("编号 STK-17254", "designation STK-17254"),
    ("latitude 22°N", "latitude 22°N"),
    ("编号", "designation"),
    ("试探性 route", "probing route"),
    ("璇试探性", "probing "),
    ("大规模 network", "large-scale network"),
    ("cause大规模", "cause large-scale"),
    ("安全态势图", "security situational map"),
    ("微妙 relaxed", "subtle relaxed"),
    ("随身 briefcase", "carried briefcase"),
    ("协助 enforcement", "cooperative enforcement"),
    ("权限 unchanged", "permissions unchanged"),
    ("追问 where", "ask where"),
    ("轮廓 against", "silhouette against"),
    ("温差 between", "temperature difference between"),
    ("无非 finding", "nothing but finding"),
    ("一个念头", "a single thought"),
    ("流通 of thought", "flow of thought"),
    ("思想的流通", "flow of thought"),
    ("书写", "writing"),
    ("编码 written", "encoded written"),
    ("型号 available", "model available"),
    ("抖动 and calm", "flickering and calm"),
    ("劃分d the boundaries", "demarcated the boundaries"),
    ("关联 between", "correlation between"),
    ("波形特征", "waveform characteristics"),
    ("微小 effect", "minute effect"),
    ("鉴定 document", "assessment document"),
    ("发作 frequency", "seizure episode frequency"),
    ("no发作", "no seizure episodes"),
    ("备忘录", "notes"),
    ("动作 of confirming", "motion of confirming"),
    ("安稳 breathing", "peaceful breathing"),
    ("画面流畅得像是本地播放", "footage smooth as local playback"),
    ("流畅得像是本地播放", "smooth as local playback"),
    ("Huawei's Institute 201离职", "Huawei's Institute 201 departure"),
    ("方案,", "approach,"),
    ("方案.", "approach."),
    ("漏洞,", "vulnerability,"),
    ("改造—it", "renovated—it"),
    ("方案\"", "approach\""),
    ("Data Heaven", "Data Haven"),
    ("念头", "thought"),
    ("轮廓", "silhouette"),
    ("关联", "correlation"),
    ("Theseizure episode", "The seizure episode"),
    ("waveform特征", "waveform characteristics"),
    ("劃分ing", "demarcating"),
    ("微小", "tiny"),
    ("语音", "voice"),
    ("陈述", "briefing"),
    ("巨大", "vast"),
    ("层级", "hierarchy"),
    ("链路", "link"),
    ("指令流", "command stream"),
    ("保存 for", "saved for"),
    ("召回 it", "recall it"),
    ("常规 electromagnetic", "conventional electromagnetic"),
    ("巨型 display", "massive display"),
    ("拼接 screens", "tiled screens"),
    ("thefootage", "the footage"),
    ("In thefootage", "In the footage"),
    ("no回头路", "no point of no return"),
    ("ice覆盖", "ice covering"),
    ("转账 records", "transfer records"),
    ("预留d", "reserved"),
    ("tampering痕迹", "tampering traces"),
    ("既定 step", "predetermined step"),
    ("expelling微弱", "expelling faint"),
    ("扩散 into", "spread into"),
    ("敏感波段", "sensitive band"),
    ("导航误差", "navigation drift"),
    ("滑行了", "slid"),
    ("drone停", "drone parked"),
    ("Awaiting指令", "Awaiting command"),
    ("终端 devices", "terminal devices"),
    ("重新 revealing", "again revealing"),
    ("埋了 trapdoors", "buried trapdoors"),
    ("尾号", "last digits"),
    ("往返 before", "round trips before"),
    ("标识 jacket", "badge jacket"),
    ("远程操控端", "remote control endpoint"),
    ("无法彻底清除", "impossible to eliminate"),
    ("具体时长", "specific duration"),
    ("state of凝固", "state of frozen"),
    ("滑动轨道", "sliding track"),
    ("automatic sliding轨道", "automatic sliding track"),
    ("情感冲击", "emotional impact"),
    ("major emotional冲击", "major emotional impact"),
    ("主镜头", "main camera"),
    ("操控.", "control."),
    ("操控端", "control endpoint"),
    ("departure实验日志", "departure experiment logs"),
    ("departureʵ", "departure experiment logs"),
    ("实验日志", "experiment logs"),
    ("If we强行注入", "If we force injection"),
    ("If weǿ", "If we force"),
    ("注 now", "inject now"),
    ("呼吸节", "breathing rhythm"),
    ("kind of呼吸", "kind of breathing"),
    ("anycorrelation", "any correlation"),
    ("there is a关联", "there is a correlation"),
    ("anyminute", "any minute"),
    ("fromdense", "from dense"),
    ("Not thought ��", "Not thought —"),
    ("offline ��", "offline —"),
    ("waiting for ��", "waiting for —"),
    ("had seen ��", "had seen —"),
    ("veins ��", "veins —"),
    ("failure ��", "failure —"),
    ("breathing ��", "breathing —"),
    ("differences��", "differences —"),
    ("itself��", "itself —"),
    ("Farhan��", "Farhan —"),
    ("occupation used comm", "occupation listed as commercial"),
    ("—theoretically", "— theoretically"),
    ("操控", "control"),
    ("指令", "command"),
    ("误差", "drift"),
    ("远程操控", "remote control"),
    ("轨道", "track"),
    ("镜头", "camera"),
    ("冲击", "impact"),
    ("凝固", "frozen"),
    ("标识", "badge"),
    ("往返", "round trip"),
    ("尾号", "suffix digits"),
    ("终端", "terminal"),
    ("微弱", "faint"),
    ("痕迹", "traces"),
    ("预留", "reserved"),
    ("转账", "transfer"),
    ("覆盖", "covering"),
    ("拼接", "tiled"),
    ("巨型", "massive"),
    ("常规", "conventional"),
    ("召回", "recall"),
    ("保存", "saved"),
    ("链路", "link"),
    ("层级", "hierarchy"),
    ("巨大", "vast"),
    ("陈述", "briefing"),
    ("语音", "voice"),
    ("微小", "tiny"),
    ("关联", "correlation"),
    ("轮廓", "silhouette"),
    ("念头", "thought"),
    ("扩散", "spread"),
    ("波段", "band"),
    ("滑", "slid"),
    ("停", "parked"),
    ("埋", "buried"),
    ("重新", "again"),
    ("既定", "predetermined"),
    ("回头", "turn-back"),
    ("底层", "underlying"),
    ("专家", "specialist"),
    ("会诊", "consultation"),
    ("远程", "remote"),
    ("异常", "anomalous"),
    ("极限", "limit"),
    ("清醒", "sober"),
    ("漏洞", "vulnerability"),
    ("方案", "approach"),
    ("改造", "renovated"),
    ("阻尼", "damping"),
    ("截取", "excerpt"),
    ("空白", "blank"),
    ("冷静", "calm"),
    ("合法", "legitimate"),
    ("试探", "probing"),
    ("编号", "designation"),
    ("大规模", "large-scale"),
    ("微妙", "subtle"),
    ("随身", "carried"),
    ("协助", "cooperative"),
    ("权限", "permissions"),
    ("温差", "temperature difference"),
    ("无非", "nothing but"),
    ("流通", "flow"),
    ("编码", "encoded"),
    ("型号", "model"),
    ("抖动", "jitter"),
    ("划分", "demarcated"),
    ("波形", "waveform"),
    ("特征", "characteristics"),
    ("发作", "seizure"),
    ("备忘录", "notes"),
    ("动作", "motion"),
    ("安稳", "peaceful"),
    ("鉴定", "assessment"),
    ("预测", "predict"),
    ("偏移", "offset"),
    ("接口", "interface"),
    ("模块", "module"),
    ("延迟", "latency"),
    ("窗口", "window"),
    ("显示", "display"),
    ("信号", "signal"),
    ("扫描", "scan"),
    ("摩擦", "friction"),
    ("发出", "produce"),
    ("沙沙", "rustling"),
    ("掠过", "swept"),
    ("云层", "cloud layer"),
    ("递减", "decreasing"),
    ("默认", "default"),
    ("排版", "layout"),
    ("密集", "dense"),
    ("接近", "approaching"),
    ("完整", "intact"),
    ("封锁", "sealed"),
    ("范围", "range"),
    ("偏", "offset"),
]

# Manual EN for known full zh dialogue lines (zh exact -> en exact)
FULL_LINES = {
    "「The board knows about Silas. The evidence you provided — we won't追问 where you got it, or why you sat on it for years before releasing it. But you need to know one thing: you have no allies left on the board. You're still the chief protocol architect, your salary unchanged, your权限 unchanged — but next time, no one will speak for you.」":
    "**「The board knows about Silas. The evidence you provided — we won't ask where you got it, or why you sat on it for years before releasing it. But you need to know one thing: you have no allies left on the board. You're still the chief protocol architect, your salary unchanged, your permissions unchanged — but next time, no one will speak for you.」**",
}


def fix_content(text: str) -> str:
    for zh, en in sorted(PHRASES, key=lambda x: -len(x[0])):
        text = text.replace(zh, en)
    for old, new in FULL_LINES.items():
        text = text.replace(old, new)
    return text


def fix_file(en_path: Path) -> int:
    zh_path = ZH_DIR / en_path.name
    lines = en_path.read_text(encoding="utf-8").splitlines(keepends=True)
    zh_lines = zh_path.read_text(encoding="utf-8").splitlines() if zh_path.exists() else []
    changed = 0
    out = []
    for i, line in enumerate(lines):
        new_line = fix_content(line.rstrip("\n"))
        # If line still has Chinese and zh parallel exists, check if entire line was copied
        if CN_RE.search(new_line) and i < len(zh_lines):
            zh_line = zh_lines[i].strip()
            if CN_RE.search(zh_line) and zh_line in new_line and len(CN_RE.findall(new_line)) > 3:
                # heavily Chinese line — skip auto (needs human); mark for grep
                pass
        new_line = new_line + ("\n" if line.endswith("\n") else "")
        if new_line != line:
            changed += 1
        out.append(new_line)
    en_path.write_text("".join(out), encoding="utf-8")
    return changed


def main():
    total = 0
    for f in sorted(EN_DIR.glob("*.md")):
        n = fix_file(f)
        if n:
            print(f"{f.name}: {n}")
            total += n
    remaining = 0
    for f in EN_DIR.glob("*.md"):
        for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            if CN_RE.search(line):
                remaining += 1
                print(f"  REMAIN {f.name}:{i}: {line[:100]}")
    print(f"Changed {total} lines; {remaining} lines still contain CJK")


if __name__ == "__main__":
    main()
